---
- name: LEAPP_NFS_DETECTED | Disable NFS temporarily for the upgrade
  vars:
    entry_title: Use of NFS detected. Upgrade can't proceed
    leapp_report_location: /var/log/leapp/leapp-report.json
  block:
    - name: LEAPP_NFS_DETECTED | Check that the leapp-report.json exists
      stat:
        path: "{{ leapp_report_location }}"
      register: leapp_report_stat

    - name: LEAPP_NFS_DETECTED | End play if no leapp report exists
      meta: end_play
      when: leapp_report_stat.stat.exists is false

    - name: LEAPP_NFS_DETECTED | Read leapp report
      slurp:
        src: "{{ leapp_report_location }}"
      register: leappreport

    - name: LEAPP_NFS_DETECTED | Parse leapp report to json
      set_fact:
        leappreportdata: "{{ leappreport.content | b64decode | from_json }}"

    - name: LEAPP_NFS_DETECTED | Find matching entries
      set_fact:
        summary: "{{ item.summary }}"
      loop: "{{ leappreportdata.entries }}"
      when: item.title is match(entry_title) and (item.summary | length > 0)

    - name: LEAPP_NFS_DETECTED | split summary
      set_fact:
        split_summary: "{{ summary.split('- NFS')[1:] | map('regex_replace', '^[\\s\\n]+', '- NFS ') | list }}"
    - name: LEAPP_NFS_DETECTED | Get fstab_entries
      set_fact:
        fstab_entries: "{{ item | split('- NFS shares found in /etc/fstab:') | last | trim | regex_findall('- ([^ ]+)', '\\1') }}"
      loop: "{{ split_summary }}"
      when: "'- NFS shares found in /etc/fstab:' in item"
    - name: LEAPP_NFS_DETECTED | Get nfs_mounts
      set_fact:
        nfs_mounts: "{{ item | split('- NFS shares currently mounted:') | last | trim | regex_findall('- ([^ ]+)', '\\1') }}"
      loop: "{{ split_summary }}"
      when: "'- NFS shares currently mounted:' in item"
    - name: LEAPP_NFS_DETECTED | Get systemd_mounts
      set_fact:
        systemd_mounts: "{{ item | split('- NFS mounts configured with systemd-mount:') | last | trim | regex_findall('- ([^ ]+)', '\\1') }}"
      loop: "{{ split_summary }}"
      when: "'- NFS mounts configured with systemd-mount:' in item"

    - name: LEAPP_NFS_DETECTED | Comment NFS shares in /etc/fstab
      loop: "{{ fstab_entries }}"
      shell: |
        entry="{{ item }}"
        grep -qF "$entry" /etc/fstab && sed -i "s|^$entry|# $entry|" /etc/fstab
      when: fstab_entries is defined

    - name: LEAPP_NFS_DETECTED | Unmount NFS Mounts
      command: umount -l {{ item }}
      loop: "{{ nfs_mounts }}"
      when: nfs_mounts is defined

...
