---
- name: LEAPP_OLD_POSTGRESQL_DATA | Backup and then remove /var/lib/pgsql/data for remediation
  block:
    - name: LEAPP_OLD_POSTGRESQL_DATA | Check if /var/lib/pgsql/data exists
      stat:
        path: /var/lib/pgsql/data
      register: pgsql_data_stat

    - name: LEAPP_OLD_POSTGRESQL_DATA | End play if /var/lib/psql/data does not exist
      meta: end_play
      when: not pgsql_data_stat.stat.exists

    - name: LEAPP_OLD_POSTGRESQL_DATA | Set backup filename with timestamp
      set_fact:
        backup_filename: pgsql_data_backup_{{ ansible_date_time.iso8601_basic_short }}.tar.gz
    - name: LEAPP_OLD_POSTGRESQL_DATA | Ensure /var/backups exists
      file:
        path: /var/backups
        state: directory

    - name: LEAPP_OLD_POSTGRESQL_DATA | Backup /var/lib/pgsql/data
      command:
        cmd: tar czvf /var/backups/{{ backup_filename }} -C /var/lib/pgsql data

    - name: LEAPP_OLD_POSTGRESQL_DATA | Remove /var/lib/pgsql/data after backup
      file:
        path: /var/lib/pgsql/data
        state: absent

...
