---
- name: LEAPP_MULTIPLE_KERNELS | Boot to latest kernel and remove old kernels
  block:
    - name: LEAPP_MULTIPLE_KERNELS | Get list of installed kernels packages sorted by the newest version
      shell: rpm -q kernel --queryformat '%{version}-%{release}.%{arch}\n' | sort -Vr
      register: installed_kernels

    - name: LEAPP_MULTIPLE_KERNELS | Check current kernel version
      shell: uname -r
      register: current_kernel

    - name: LEAPP_MULTIPLE_KERNELS | Set default kernel to latest
      shell: grubby --set-default /boot/vmlinuz-{{ installed_kernels.stdout_lines[0] }}
      when: installed_kernels.stdout_lines[0] != current_kernel.stdout

    - name: LEAPP_MULTIPLE_KERNELS | Reboot into new kernel
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true
      when: installed_kernels.stdout_lines[0] != current_kernel.stdout

    - name: LEAPP_MULTIPLE_KERNELS | Wait for reboot
      wait_for_connection: delay=15 timeout=60
      become: false
      when: installed_kernels.stdout_lines[0] != current_kernel.stdout

    - name: LEAPP_MULTIPLE_KERNELS | Remove old kernels
      yum:
        name: LEAPP_MULTIPLE_KERNELS | kernel-core-{{ item }}
        state: absent
      loop: "{{ installed_kernels.stdout_lines[1:] }}"

    - name: LEAPP_MULTIPLE_KERNELS | Print the list of installed kernels
      debug:
        var: installed_kernels.stdout_lines

...
