---
- name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Adjust openssl.cnf configuration for default_modules
  block:
    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Check if openssl.cnf exists
      stat:
        path: /etc/pki/tls/openssl.cnf
      register: openssl_cnf_stat

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | End execution of playbook if openssl.cnf does not exist
      meta: end_host
      when: openssl_cnf_stat.stat.exists is false

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Get content of openssl.cnf
      slurp:
        src: /etc/pki/tls/openssl.cnf
      register: openssl_cnf_stat

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Comment out old openssl_conf line
      shell: sed -i 's/^openssl_conf/#openssl_conf/g' /etc/pki/tls/openssl.cnf

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Comment out old [ default_modules ] block
      shell: sed -i '/^\s*\[\s*default_modules\s*\]/,/\[/ { /^\[/!s/^/#/; /^\s*\[\s*default_modules\s*\]/s/^/#/ }' /etc/pki/tls/openssl.cnf

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Comment out old [ ssl_module ] block
      shell: sed -i '/^\s*\[\s*ssl_module\s*\]/,/\[/ { /^\[/!s/^/#/; /^\s*\[\s*ssl_module\s*\]/s/^/#/ }' /etc/pki/tls/openssl.cnf

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Comment out old [ crypto_policy ] block
      shell: sed -i '/^\s*\[\s*crypto_policy\s*\]/,/\[/ { /^\[/!s/^/#/; /^\s*\[\s*crypto_policy\s*\]/s/^/#/ }' /etc/pki/tls/openssl.cnf

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Add new openssl_conf line
      blockinfile:
        path: /etc/pki/tls/openssl.cnf
        insertbefore: BOF
        block: |
          openssl_conf = default_modules
        state: present
        backup: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - LEAPP NON STANDARD OPENSSL CONFIG - openssl_conf"

    - name: LEAPP_NON_STANDARD_OPENSSL_CONFIG | Add new openssl_conf line and [ default_modules ] block
      blockinfile:
        path: /etc/pki/tls/openssl.cnf
        block: |
          [ default_modules ]
          ssl_conf = ssl_module
          [ ssl_module ]
          system_default = crypto_policy
          [ crypto_policy ]
          .include /etc/crypto-policies/back-ends/opensslcnf.config
        state: present
        backup: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - LEAPP NON STANDARD OPENSSL CONFIG - default_modules"

...
