---
- name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Unload kernel drivers which have been removed in next RHEL release
  vars:
    leapp_report_location: /var/log/leapp/leapp-report.json
    entry_title_pattern: Leapp detected loaded kernel drivers which have been removed in RHEL \d+. Upgrade cannot proceed.
  block:
    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Check that the leapp-report.json exists
      stat:
        path: "{{ leapp_report_location }}"
      register: leapp_report_stat

    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | End execution of playbook if leapp report does not exist
      meta: end_host
      when: leapp_report_stat.stat.exists is false

    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Read leapp report
      slurp:
        src: "{{ leapp_report_location }}"
      register: leappreport

    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Parse leapp report to json
      set_fact:
        leappreportdata: "{{ leappreport.content | b64decode | from_json }}"

    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Find entry in leapp report
      set_fact:
        leapp_entry: "{{ item }}"
      loop: "{{ leappreportdata.entries }}"
      when: item.title is match(entry_title_pattern)

    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Parse summary to obtain list of modules
      set_fact:
        unsupported_modules: "{{ leapp_entry.summary | regex_findall('(?<=- ).*') }}"
      when: leapp_entry is defined

    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Print unsupported modules
      debug:
        var: unsupported_modules

    - name: LEAPP_LOADED_REMOVED_KERNEL_DRIVERS | Unload unsupported modules
      command: modprobe -r "{{ item }}"
      loop: "{{ unsupported_modules }}"
      when: unsupported_modules is defined

...
