---
- name: LEAPP_NEWEST_KERNEL_NOT_IN_USE | Boot to latest kernel
  block:
    - name: LEAPP_NEWEST_KERNEL_NOT_IN_USE | Get list of installed kernels packages sorted by the newest version
      shell: rpm -q kernel --queryformat '%{version}-%{release}.%{arch}\n' | sort -Vr
      register: installed_kernels

    - name: LEAPP_NEWEST_KERNEL_NOT_IN_USE | Set default kernel to latest
      shell: grubby --set-default /boot/vmlinuz-{{ installed_kernels.stdout_lines[0] }}

    - name: LEAPP_NEWEST_KERNEL_NOT_IN_USE | Reboot into new kernel
      shell: sleep 2 && shutdown -r now
      async: 1
      poll: 0
      ignore_errors: true

    - name: LEAPP_NEWEST_KERNEL_NOT_IN_USE | Wait for reboot
      wait_for_connection: delay=15 timeout=60
      become: false

...
